server:
  port: 8401
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: xf-service


management:
  endpoints:
    web:
      exposure:
        include: '*'
