server:
  port: 8801


spring:
  application:
    name: xf-stream-provider
  cloud:
    stream:
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder:
            - ${spring.cloud.stream.binders.defaultRabbit} # 设置要绑定的消息服务的具体设置

      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.31.130
                port: 15672
                username: admin
                password: admin

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    #prefer-ip-address: true  #显示IP地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: mq-provider-service
    #eureka客户端向服务端发送心跳的间隔
    lease-renewal-interval-in-seconds: 10
    #eureka服务端收到最后一次心跳后的等待时间间隔上线，超过立即剔除
    lease-expiration-duration-in-seconds: 20

