server:
  port: 9527

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    #prefer-ip-address: true  #显示IP地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群
  instance:
    prefer-ip-address: true
    #instance-id: xf-gateway-service
    #eureka客户端向服务端发送心跳的间隔
    lease-renewal-interval-in-seconds: 1
    #eureka服务端收到最后一次心跳后的等待时间间隔上线，超过立即剔除
    lease-expiration-duration-in-seconds: 2


#路由规则
spring:
  cloud:
    gateway:
      routes:
        - id: xf-order
          uri: lb://xf-order  #路由负载均衡
          predicates:
              - Path=/order/greeting
#              - Cookie=username,xf
      discovery:
        locator:
          enabled: true #开启从注册中心创建路由功能，利用微服务名进行路由
  application:
    name: xf-gateway
